use super::*;
use crate::backend::db::fixtures;
use diesel_async::SimpleAsyncConnection;

#[tokio::test]
#[ignore = "requires isolated FEDKR_TEST_DATABASE_URL"]
async fn catalog_search_reaches_beyond_old_caps_with_stable_pages_and_real_labels() {
    let db = fixtures::database().await;
    let marker = format!("catalog-{}", uuid::Uuid::new_v4().simple());
    let mut conn = db.pool.get().await.unwrap();
    diesel::sql_query("INSERT INTO catalog_categories(id,name,label,emoji,display_order,inserted_at,updated_at)
        SELECT -abs(hashtextextended($1||n::text,11)), $1||'-kind-'||lpad(n::text,3,'0'), '검토 종류 '||n::text,'◇',-100000+n,now(),now() FROM generate_series(1,205) n")
        .bind::<Text,_>(&marker).execute(&mut conn).await.unwrap();
    diesel::sql_query("INSERT INTO catalog_software(id,name,display_name,description,category_tag,categories,logo_key,is_featured,display_order,inserted_at,updated_at)
        SELECT -abs(hashtextextended($1||n::text,19)), $1||'-tool-'||lpad(n::text,3,'0'),
        CASE WHEN n=511 THEN $1||' 의미%_+' ELSE $1||' 같은 이름' END,
        '검토용 소개', $1||'-kind-205', CASE WHEN n=512 THEN ARRAY[]::text[] ELSE ARRAY[$1||CASE WHEN n%2=0 THEN '-kind-205' ELSE '-kind-001' END] END,
        'private/never-expose',false,0,now(),now() FROM generate_series(0,512) n")
        .bind::<Text,_>(&marker).execute(&mut conn).await.unwrap();
    drop(conn);
    let mut q = CatalogQuery {
        query: marker.clone(),
        ..Default::default()
    };
    let first = db.search_catalog(&q).await.unwrap();
    assert_eq!(first.total, 513);
    assert_eq!(first.software.len(), 24);
    assert_eq!(first.kinds.categories.len(), 12);
    assert!(first.has_next && first.kinds.has_next);
    assert!(
        db.public_catalog().await.unwrap().truncated,
        "fixture exceeds old client-side catalog cap"
    );
    assert!(
        first
            .labels
            .iter()
            .any(|k| k.name == format!("{marker}-kind-205")),
        "off-page category labels are resolved independently"
    );
    assert!(!serde_json::to_string(&first)
        .unwrap()
        .contains("never-expose"));
    let mut seen = std::collections::HashSet::new();
    for page in 0..22 {
        q.page = page;
        let result = db.search_catalog(&q).await.unwrap();
        assert_eq!(result.total, 513);
        assert_eq!(result.has_next, page < 21);
        for software in result.software {
            assert!(
                seen.insert(software.name),
                "no duplicates across tied sort values"
            );
        }
    }
    assert_eq!(seen.len(), 513);
    q.page = 0;
    q.category = format!("{marker}-kind-205");
    let filtered = db.search_catalog(&q).await.unwrap();
    assert_eq!(
        filtered.total, 257,
        "legacy empty-array category_tag fallback is included"
    );
    q.query = format!("{marker}-tool-512");
    let last = db.search_catalog(&q).await.unwrap();
    assert_eq!(last.software.len(), 1);
    assert_eq!(last.software[0].categories, vec![q.category.clone()]);
    q.category.clear();
    q.query = "의미%_+".into();
    assert_eq!(
        db.search_catalog(&q).await.unwrap().total,
        1,
        "wildcard-looking search remains literal Korean text"
    );
    q.query = marker.clone();
    q.kind_page = 17;
    assert!(db
        .search_catalog(&q)
        .await
        .unwrap()
        .kinds
        .categories
        .iter()
        .any(|k| k.name == format!("{marker}-kind-205")));
    q.page = 10_000;
    let empty = db.search_catalog(&q).await.unwrap();
    assert_eq!(empty.total, 513);
    assert!(empty.software.is_empty());
    assert!(!empty.has_next);
    q.page = 10_001;
    assert!(db.search_catalog(&q).await.is_err());
    let mut conn = db.pool.get().await.unwrap();
    // Fixed marker generated by this test, never a user-provided SQL string.
    for table in ["catalog_software", "catalog_categories"] {
        diesel::sql_query(format!("DELETE FROM {table} WHERE strpos(name,$1)=1"))
            .bind::<Text, _>(&marker)
            .execute(&mut conn)
            .await
            .unwrap();
    }
    conn.batch_execute("SELECT 1").await.unwrap();
}
